name: AcceptanceTest

on:
  workflow_run:
    workflows: [ "CommitStage" ]
    types:
      - completed

concurrency:
  group: acceptance-stage

jobs:
  acceptance:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: project
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Aceptance Test
        run: |
          cd project/
          mvn clean package