name: CommitStage

on:
  push:

concurrency:
  group: commit-stage

jobs:
  commit:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: project
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build
        run: |
          cd project/
          mvn clean package
      - name: Push
        run: |
          cd project/
          mvn clean package